### ISSUE TITLE
Add Storage Requirement to Installation Instructions

### ISSUE THREAD

**Issue by mstietencron** [eu-nebulous/nebulous#11]
The needed file system size should be mentioned under "Prerequisites" on https://github.com/eu-nebulous/nebulous/wiki/1.-Installation.

**Comment by jmarchel7bulls** [comment]
Added requirement of 100 Gb.
I looked at the cluster and there is volume attached of 100 Gb to each worker (worker host one environent). We using less in reality, but it is safer to use such number as 100.
