### ISSUE TITLE
Instructions for setting up OpenStack are missing

### ISSUE THREAD

**Issue by ankicabarisic** [eu-nebulous/nebulous#12]
As we used Open Stack for testing sessions it is surprising to see that there are no instructions on how to set up this cloud provider. 
https://github.com/eu-nebulous/nebulous/wiki/2.1-Managing-cloud-providers#openstack

Is this going to be tested by open calls or use cases?

**Comment by robert-sanfeliu** [comment]
No UC/OC expressed clear intentions on using theyr own OpenStack instance. Anyway, it remains to be documented.

@jmarchel7bulls can you document it with the help of @rudi ?

**Comment by jmarchel7bulls** [comment]
The main question is if the UiO will share their openstack resources. There is no need to do so, at least in my opinion. @rudi @GeirHo please share your view on this.

**Comment by rudi** [comment]
Share openstack resources to whom, and for what purpose?

**Comment by robert-sanfeliu** [comment]
No, this is not about sharing OpenStack. This is about documenting if there is any specific configuration to be done on an OpenStack installation for it to be used by NebulOuS to deploy apps.

**Comment by rudi** [comment]
Ah ok, then I won't be much help in documenting this, sorry. I only ever followed the Postman recipes that Ali gave me.

**Comment by yoctozepto** [comment]
@jmarchel7bulls This should be documented in general terms, not using the UiO's credentials
.
