### ISSUE TITLE
List of available Netdata Sensors and configuration Examples

### ISSUE THREAD

**Issue by mstietencron** [eu-nebulous/nebulous#13]
The documentation should have a list of the available netdata sensors and how they can / should be configured in the GUI.

**Comment by ipatini** [comment]
If you mean metrics provided by Netdata, you can find a sample list in the corresponding wiki page (https://github.com/eu-nebulous/nebulous/wiki/3.1.3.2-Publishing-system-and-cluster-metrics-using-Netdata). It also provides a description of how to configure a raw metric collecting its metric values from Netdata.

If this is not what you need please reopen the issue.

**Comment by ipatini** [comment]
For the sample netdata metrics list please check at the appendix (at the end of the page)
