### ISSUE TITLE
Missing installation instructions for ProActive Scheduler

### ISSUE THREAD

**Issue by yoctozepto** [eu-nebulous/nebulous#14]
As ProActive Scheduler is a core, independent component of NebulOuS, it must be installed separately by NebulOuS operators. However, there is no mention of it in the installation pages on the wiki. We need to have its installation and configuration for/in NebulOuS documented (e.g., also how to get SAL to "see" it).

Please @ankicabarisic drive this effort with possibly highest priority. @jmarchel7bulls will help of course.

(cc @robert-sanfeliu)

**Comment by ankicabarisic** [comment]
Installation instructions have been provided since 11/2023:
https://openproject.nebulouscloud.eu/projects/nebulous-collaboration-hub/wiki/creating-a-proactive-server-machine-on-top-uio-openstack

**Comment by yoctozepto** [comment]
@ankicabarisic Thanks for providing the link but please do not close. That page is very NREC-centric (and thus private as well). We need a general installation docs in the NebulOuS wiki.

**Comment by ankicabarisic** [comment]
ok, please note that for anyone who wants to instal proactive with their licence, it is to send an official request to AE for approval. we had a ticket regarding this and communicated this over slack:
https://openproject.nebulouscloud.eu/projects/nebulous-collaboration-hub/work_packages/509/activity

Also, note that general documentation regarding installing ProActive can be found here - there is special section on how to do it on Kubernetes:
http://158.39.77.68:8880/doc/admin/ProActiveAdminGuide.html#_run_the_proactive_scheduler

**Comment by robert-sanfeliu** [comment]
@yoctozepto : will it be sufficient to 
 include a link to http://158.39.77.68:8880/doc/admin/ProActiveAdminGuide.html#_install_and_start_proactive_using_kubernetes in the installation instructions for NebulOuS?
 
 (cc @mstietencron)

**Comment by yoctozepto** [comment]
We should not link to that specific address.

I will try to repro that instruction and integrate it with the rest of the installation.

**Comment by ankicabarisic** [comment]
Hi, if I am not wrong the installation I see on wiki was performed as a Linux installation on `/opt/proactive` not one using Kubernetes: http://158.39.77.68:8880/doc/admin/ProActiveAdminGuide.html#_how_to_install_proactive_on_linux 

@yoctozepto can you confirm? This we need to understand to make the update...

**Comment by yoctozepto** [comment]
@ankicabarisic I didn't install it but I know it was done before the k8s-based installation was offered so that's most likely. You may as well nuke the current installation and switch it to k8s-based. I am going to try the k8s-based deployment for our evaluators.

**Comment by ankicabarisic** [comment]
@yoctozepto ok, but to update the current one as I see we need to:
1. backup  the configuration and data  (DB, workflows, etc) from the old ProActive installation 
2. rerun install.sh script: `$ sudo $PROACTIVE_HOME/tools/install.sh`

I guess you or @jmarchel7bulls can do this?
The process shouldn't take too long

**Comment by yoctozepto** [comment]
> @yoctozepto ok, but to update the current one as I see we need to:
> 
> 1. backup  the configuration and data  (DB, workflows, etc) from the old ProActive installation
> 2. rerun install.sh script: `$ sudo $PROACTIVE_HOME/tools/install.sh`
> 
> I guess you or @jmarchel7bulls can do this? The process shouldn't take too long

I can't. Please catch Janek on Slack. This thread is not about updating that particular instance of ProActive. ;-)

**Comment by yoctozepto** [comment]
I've updated https://github.com/eu-nebulous/helmfile

The installer is very straightforward once obtained.

**Comment by ankicabarisic** [comment]
Just to note that I send the following instructions for ProActive installation:

To install it follow NebulOuS installation instructions: https://openproject.nebulouscloud.eu/projects/nebulous-collaboration-hub/wiki/creating-a-proactive-server-machine-on-top-uio-openstack#install-proactive

Note that the admin password is set during the installation process. Later to have a different user you can follow this guide: https://openproject.nebulouscloud.eu/projects/nebulous-collaboration-hub/wiki/proactive-in-nebulous-k8s#manage-proactive-users

Please keep me informed if there is other documentation for this purpose to be shared with Open Calls and Use case partners when they request the ProActive licence.

**Comment by ankicabarisic** [comment]
@robert-sanfeliu @yoctozepto Is this documentation provided for Open Calls?

**Comment by robert-sanfeliu** [comment]
@yoctozepto: Can you integrate the documentation on how to install proactive provided in this thread with the rest of documentation on how to install NebulOuS that can be found on the Github wiki?

**Comment by jchmielewska** [comment]
I've added the instruction here https://github.com/eu-nebulous/nebulous/wiki/1.1-Installation-Walk%E2%80%90trough-for-Development-&-Evaluation

@ankicabarisic could you confirm that everything is there?

**Comment by ankicabarisic** [comment]
It still misses part on how to set the user and password for ProActive (It should be the same as how is set in Nebulous installation to establish a sal connection to proactive).

The user admin is set as the default during installation. here is to how to set custom users: https://openproject.nebulouscloud.eu/projects/nebulous-collaboration-hub/wiki/proactive-in-nebulous-k8s#manage-proactive-users


In the case they are expected to check the ProActive logs, the process is here: https://openproject.nebulouscloud.eu/projects/nebulous-collaboration-hub/wiki/proactive-in-nebulous-k8s#proactive-logs

How to restart ProActive to be updated to this: https://openproject.nebulouscloud.eu/projects/nebulous-collaboration-hub/wiki/proactive-in-nebulous-k8s#restart-proactive

**Comment by jchmielewska** [comment]
done

**Comment by ankicabarisic** [comment]
@jchmielewska 
Can you clearly distinguish the sections regarding ProActive installation, user management, checking logs of running proactive and restarting it to be at the same level? Like it is now is not clear.
Further, I believe that the link to the nebulous wiki for developers which you included is not available to open calls, so please if you want to introduce the one from the proactive scheduler or just remove it (as I think you want to have a unique way of installing proactive)

**Comment by ankicabarisic** [comment]
also remove this as it is specific to nebulous access: 

To copy local logs for error reporting is necessary to go to local machine and use the following command:

scp -i scheduler.key ubuntu@158.39.77.68:connector-iaas.txt ~/connector-iaas.txt

**Comment by ankicabarisic** [comment]
I guess quite a bit is missing on installation instructions:
![image](https://github.com/user-attachments/assets/cca1fbd3-4e35-4203-9565-1c32acfd1f3d)
![image](https://github.com/user-attachments/assets/fbe0c3b5-ea10-49b5-940b-479611f876a3)

**Comment by jchmielewska** [comment]
I've edited the instruction and it's not missing any crucial information, we don't need to put everything from Wiki there and I didn't want to clutter the instruction.

**Comment by ankicabarisic** [comment]
@jchmielewska check the logs during installation as you wrote it can be misinterpreted as a command which is not, it is location of installation logs ;)
To check the server GUI -> Check the ProActive server GUI (not to think it is nebulous one)
