### ISSUE TITLE
Support for automatic SAL deployment/integration in Nebulous

### ISSUE THREAD

**Issue by ankicabarisic** [eu-nebulous/nebulous#16]
We asked on several places regarding how the automatic deployment of SAL is to be handled, but we have had no answer on this matter.  

The idea was that SAL deployment should be automatically supported by the Nebulous ci/cd pipeline, and to provide proper support for this we were asked to implement changes in our internal ci/cd pipeline:
https://bugs.launchpad.net/nebulous/+bug/2064918

It has been 2 months since this was provided and documented on the [WIKI](https://openproject.nebulouscloud.eu/projects/nebulous-collaboration-hub/wiki/sal-deployment#sal-release-info), however, we still do not have any information on how the automatic deployment will be supported and when.

This is a blocker for any updated version of SAL to be automatically set to the expected Nebulous environment so that it can be tested.

**Comment by yoctozepto** [comment]
Interesting timing. See https://github.com/eu-nebulous/helm-charts/pull/8

That was one of prereqs to get proper automation for SAL. We asked for this last year but then the priorities shifted so I guess this was lost for the time. Anyhow, this gets us closer to covering any gaps we have in deployment...

> We asked on several places regarding how the automatic deployment of SAL is to be handled, but we have had no answer on this matter.

GitHub works best.

> The idea was that SAL deployment should be automatically supported by the Nebulous ci/cd pipeline, and to provide proper support for this we were asked to implement changes in our internal ci/cd pipeline: https://bugs.launchpad.net/nebulous/+bug/2064918

That's right! This was seemingly lost for the time afterwards...

> It has been 2 months since this was provided and documented on the [WIKI](https://openproject.nebulouscloud.eu/projects/nebulous-collaboration-hub/wiki/sal-deployment#sal-release-info), however, we still do not have any information on how the automatic deployment will be supported and when.

For all other components we support it with timestamps. This allows for more than one release a day, unlike your proposal. Please follow our practice. The current code is for GHA (it was for Zuul previously):

https://github.com/eu-nebulous/github-actions/blob/c4bb1e0c40371ad8cf1146894b19bf1c209c0e6f/.github/workflows/build-and-push-container-image.yml#L43-L56

(note we have, as documented in wiki, **main** for the current development and **r1** for the 1st release stream -- release artifacts can thus be updated [read: fixed] as well)

> This is a blocker for any updated version of SAL to be automatically set to the expected Nebulous environment so that it can be tested.

Agreed. If not a blocker, it at least makes it too clunky to bother.

I will assign you to this issue now to let you handle your part. I will keep myself to work on adopting and polishing the chart (as needed).

**Comment by ankicabarisic** [comment]
Just to keep this explanation from you here for validation part later.
"the automation regularly scans the image repositories and updates the image tags (in the flux repo) for the cd environment; the other environments are updated semi-automatically, flux can propose changes as PRs which can be merged by humans and/or humans can change image versions themselves;"

let me know when sal automation is done and i validate for cd ;)

**Comment by yoctozepto** [comment]
The other agreement we went with is to keep your current versioning scheme (date) to lessen your burden at the cost of limiting yourselves to up to 1 image update per day.

**Comment by yoctozepto** [comment]
Implemented in CD.
