### ISSUE TITLE
UiO Open Stack authentification doesn't work anymore

### ISSUE THREAD

**Issue by ankicabarisic** [eu-nebulous/nebulous#18]
Hi, 

I am having authentication issues to access my Open Stack account:
![image](https://github.com/user-attachments/assets/6c6e1265-d096-487e-8006-fd78548ff7da)

This is log I receive from the server if I want to retrive the images for cloud with my account:
```
:POST https://api.nrec.no:5000/v3/auth/tokens HTTP/1.1 -> HTTP/1.1 401 UNAUTHORIZED
org.jclouds.rest.AuthorizationException: POST https://api.nrec.no:5000/v3/auth/tokens HTTP/1.1 -> HTTP/1.1 401 UNAUTHORIZED
```

Can you please check if something has changed?

Thank you

**Comment by rudi** [comment]
Hello Ankica, the text in the image you posted contains instructions on how to fix this (basically, remove line 4 of ~/.ssh/known_hosts, either with a text editor or with the command that is the third-to-last line of the text in the image).  Did you try to follow these instructions?

**Comment by rudi** [comment]
If you know who administers the 158.39.201.189 server, you could contact them and check if they changed the host key, which is the reason you can't login anymore.  You could also disable strict checking (this is what the second-to-last line tells you).

**Comment by ankicabarisic** [comment]
Hi Rudi, sorry for the second error, it was just me trying access the server I had before on Open Stack. 

Actually problem is in fist error where I just ask the `openstack server list `and it returns Authentification error. Usually I would get list of servers.

Same happen when I make a call over SAL to add Open Stack cloud using my cardentials -> JClouds give me Authetification error.  This used to work fine before.
If I use your cardentials and the key everything works fine. 

So I need to know if something changed with my authentification. It was @GeirHo who gave me my access. Don't know if you know how to check if it is still valid. 

This is not a blocker but I use this account sometimes to do some tests so would be nice to have it working :)

**Comment by rudi** [comment]
Ah ok, sorry for my misunderstanding!  I think @GeirHo has to answer this -- if it becomes more urgent I could contact nrec support but in that case I will need a call with you beforehand to clarify.

**Comment by GeirHo** [comment]
Sorry, Ankica!

I will try to check this over the weekend to see if I can solve it somehow. If not we will have to wait for NREC support as Rudi said and I do not know if they are very responsive now during vacation.

All the best for a nice and quiet non-working weekend (the benefit of passwords not working...)!

--- Geir

--

Geir Horn

University of Oslo



Faculty of Mathematics and Natural Sciences

***@***.******@***.***>
Ole-Johan Dahls hus (10465)

+47 93 05 93 35

Postboks 1080 Blindern

Zoom, Viber, Signal, SIP
0316 Oslo

Skype: GeirHorn

Norway

















On Fri, 2024-07-19 at 06:43 -0700, Ankica Barisic wrote:

Hi Rudi, sorry for the second error, it was just me trying access the server I had before on Open Stack.

Actually problem is in fist error where I just ask the openstack server list and it returns Authentification error. Usually I would get list of servers.

Same happen when I make a call over SAL to add Open Stack cloud using my cardentials -> JClouds give me Authetification error. This used to work fine before.
If I use your cardentials and the key everything works fine.

So I need to know if something changed with my authentification. It was @GeirHo<https://github.com/GeirHo> who gave me my access. Don't know if you know how to check if it is still valid.

This is not a blocker but I use this account sometimes to do some tests so would be nice to have it working :)

**Comment by ankicabarisic** [comment]
Hello Geir as I mentioned it is not urgent but would be nice to have it working again for testing purposes.
I will also be away next week, so let's see if it can be resolved sometime in August. Let me know, and enjoy your time off!

**Comment by ankicabarisic** [comment]
@GeirHo did you receive any information regarding this?

**Comment by GeirHo** [comment]
Noup, but I understood it was not urgent.

I have asked the support if they can reset and give you a new password. Hopefully that will work! However, all over UiO there is now a push for 2FA, and I do sincerely hope that they have not disabled direct API access for OpenStack!

All the best,

--- Geir

--

Geir Horn

University of Oslo



Faculty of Mathematics and Natural Sciences

***@***.******@***.***>
Ole-Johan Dahls hus (10465)

+47 93 05 93 35

Postboks 1080 Blindern

Zoom, Viber, Signal, SIP
0316 Oslo

Skype: GeirHorn

Norway

















On Tue, 2024-08-27 at 02:20 -0700, Ankica Barisic wrote:

@GeirHo<https://github.com/GeirHo> did you receive any information regarding this?

**Comment by ankicabarisic** [comment]
Change of password resolved this problem. Thank you!
