### ISSUE TITLE
Published NebulOuS release has outdated component versions

### ISSUE THREAD

**Issue by ankicabarisic** [eu-nebulous/nebulous#5]
In https://github.com/eu-nebulous/nebulous/wiki/1.-Installation  the release of Nebulous manifest does not correspond to the release version of the components. For SAL I can see you are using the release manifest from before Brussels, and not the release version of the SAL image as documented in Nebulous Wiki. (https://drive.google.com/file/d/1zTcFHzqHkflvebHE9es04wA4aL0H45pG/view?usp=drive_link )
dates are corresponding to 23rd of April

**Comment by jmarchel7bulls** [comment]
The dates are not so important, because we pulling charts from the repository. If version of sal is invalid please take care of it yourself. Here is the repo https://github.com/eu-nebulous/sal. You know best what version should be uploaded.

**Comment by ankicabarisic** [comment]
@robert-sanfeliu as you requested this to be opened as a ticket Please validate 
I find the answer inappropriate as the version handling of the components is handled by the integrator and not AE. SAL was just to illustrate the problem with the published repository.

**Comment by robert-sanfeliu** [comment]
@ankicabarisic please provide the link to "and not the release version of the SAL image as documented in Nebulous Wiki."  Do you refer to https://openproject.nebulouscloud.eu/projects/nebulous-collaboration-hub/wiki/sal-in-nebulous-k8s ? 

If yes, there is an statement that says  "[K8s environment](https://openproject.nebulouscloud.eu/projects/nebulous-collaboration-hub/wiki/accessing-the-nebulous-dev-k8s#environment-details-please-do-not-skip) consists of several namespaces with a specific purpose. See [SAL deployment manifest](https://openproject.nebulouscloud.eu/projects/nebulous-collaboration-hub/wiki/sal-deployment-info) for more on how SAL is deployed."

However, the link to "SAL deployment manifest" is broken. 

Please, clarify

**Comment by ankicabarisic** [comment]
@robert-sanfeliu This ticket was based on the fact that the nebulous release manifest did not contain the release version of components. Did the release manifest get updated, I see google link from ticket not existing anymore.

Regarding SAL, info regarding images to be used in deployment is here: https://openproject.nebulouscloud.eu/projects/nebulous-collaboration-hub/wiki/sal-deployment#sal-release-info
The ticket where we were requested to change our ci/cd pipeline is here: https://bugs.launchpad.net/nebulous/+bug/2064918
However, this is another issue for which we have a bug report and we expect that as we implemented it to be used in nebulous.

**Comment by jmarchel7bulls** [comment]
@ankicabarisic i don't know why you refered to integrator here. Subject of subject is something diffrent, describtion of issue is something diffrent too. Why you refering to integrator for manual installation of nebulous. We make integrator for nrec envrionmets.

**Comment by jmarchel7bulls** [comment]
https://github.com/eu-nebulous/nrec-flux-config We decided to make integrator public for you to understand it better

**Comment by jmarchel7bulls** [comment]
In the manual installation we are using helm charts and also https://github.com/eu-nebulous/sal/blob/main/resources/deployment.yaml, so i think dev is the current version because it was pushed 1 day ago. If you do not find version of this tag appropriate please change this yourself in the https://github.com/eu-nebulous/sal/blob/main/resources/deployment.yaml. What i want point out it is not release r1 installation, the r1 installation will be published when it will be validated by use cases, because we still can find some blocking bugs.

**Comment by ankicabarisic** [comment]
In https://github.com/eu-nebulous/nebulous/wiki/1.-Installation the release of Nebulous manifest does not correspond to the release version of the components.

This was the ticket about. I see there is no more Google Drive Nebulous manifest (the link is not valid anymore).

Regarding r1, thank you for updating me, however, the info we had was that r1 was released at the beginning of June (before the plenary in Barcelona).
