### ISSUE TITLE
Can't register new cloud provider

### ISSUE THREAD

**Issue by Iqqdd99** [eu-nebulous/nebulous#55]
# Environment
Default installation of Nebulous using the helmfile.

# Problem
Can't register new cloud providers, the form doesn't show the different cloud providers (aws, openstack...).

![imagen](https://github.com/user-attachments/assets/5c79b52f-ec86-4096-b477-46427ac12344)

**Comment by robert-sanfeliu** [comment]
This is duplicated of: https://github.com/eu-nebulous/gui/issues/13 and should be already fixed

**Comment by robert-sanfeliu** [comment]
Tested by Francisco from TiD
