### ISSUE TITLE
Proactive installation documentation

### ISSUE THREAD

**Issue by Iqqdd99** [eu-nebulous/nebulous#56]
Nebulous fails to deploy nodes if Proactive is configured to use the pnp protocol instead of pamr.

**Comment by ankicabarisic** [comment]
In installation instructions it is documented that the pamr protocol should be selected: https://openproject.nebulouscloud.eu/projects/nebulous-collaboration-hub/wiki/creating-a-proactive-server-machine-on-top-uio-openstack#step-12-unzip-and-install-the-server
