### ISSUE TITLE
Improve documentation on STOMP  EMS Topic convetions

### ISSUE THREAD

**Issue by robert-sanfeliu** [eu-nebulous/nebulous#7]
Improve documentation on maping between metric names and topics to be used when publishing metrics to EMS using STOMP.
Considere:
- topic name restrictions
- scaping dashes, etc...

https://github.com/eu-nebulous/nebulous/wiki/3.1.3.2-Publishing-application-specific-metrics-using-STOMP

**Comment by robert-sanfeliu** [comment]
Clearly mention that topic to be used must be of the form:

/topic/<name_of_the_metric>_SENSOR

**Comment by ipatini** [comment]
Documentation has been updated.
