### ISSUE TITLE
Improve NebulOuS Installation Step 5 code

### ISSUE THREAD

**Issue by mstietencron** [eu-nebulous/nebulous#8]
command for step 5 is incomplete, only zip file url is given.

download from gdrive works e.g. with following command:
`curl -L "https://drive.usercontent.google.com/download?id=1zTcFHzqHkflvebHE9es04wA4aL0H45pG&confirm=xxx" --output ./nebulous.zip`

**Comment by ankicabarisic** [comment]
@mstietencron note this: https://github.com/eu-nebulous/nebulous/issues/5

**Comment by jmarchel7bulls** [comment]
updated https://github.com/eu-nebulous/nebulous/wiki/1.-Installation
